extends RefCounted

var vrm_to_human_bone: Dictionary = {"hips": "Hips", "spine": "Spine", "chest": "Chest", "upperChest": "UpperChest", "neck": "Neck", "head": "Head", "leftEye": "LeftEye", "rightEye": "RightEye", "jaw": "Jaw", "leftShoulder": "LeftShoulder", "leftUpperArm": "LeftUpperArm", "leftLowerArm": "LeftLowerArm", "leftHand": "LeftHand", "leftThumbMetacarpal": "LeftThumbMetacarpal", "leftThumbProximal": "LeftThumbProximal", "leftThumbDistal": "LeftThumbDistal", "leftIndexProximal": "LeftIndexProximal", "leftIndexIntermediate": "LeftIndexIntermediate", "leftIndexDistal": "LeftIndexDistal", "leftMiddleProximal": "LeftMiddleProximal", "leftMiddleIntermediate": "LeftMiddleIntermediate", "leftMiddleDistal": "LeftMiddleDistal", "leftRingProximal": "LeftRingProximal", "leftRingIntermediate": "LeftRingIntermediate", "leftRingDistal": "LeftRingDistal", "leftLittleProximal": "LeftLittleProximal", "leftLittleIntermediate": "LeftLittleIntermediate", "leftLittleDistal": "LeftLittleDistal", "rightShoulder": "RightShoulder", "rightUpperArm": "RightUpperArm", "rightLowerArm": "RightLowerArm", "rightHand": "RightHand", "rightThumbMetacarpal": "RightThumbMetacarpal", "rightThumbProximal": "RightThumbProximal", "rightThumbDistal": "RightThumbDistal", "rightIndexProximal": "RightIndexProximal", "rightIndexIntermediate": "RightIndexIntermediate", "rightIndexDistal": "RightIndexDistal", "rightMiddleProximal": "RightMiddleProximal", "rightMiddleIntermediate": "RightMiddleIntermediate", "rightMiddleDistal": "RightMiddleDistal", "rightRingProximal": "RightRingProximal", "rightRingIntermediate": "RightRingIntermediate", "rightRingDistal": "RightRingDistal", "rightLittleProximal": "RightLittleProximal", "rightLittleIntermediate": "RightLittleIntermediate", "rightLittleDistal": "RightLittleDistal", "leftUpperLeg": "LeftUpperLeg", "leftLowerLeg": "LeftLowerLeg", "leftFoot": "LeftFoot", "leftToes": "LeftToes", "rightUpperLeg": "RightUpperLeg", "rightLowerLeg": "RightLowerLeg", "rightFoot": "RightFoot", "rightToes": "RightToes"}


func _init(is_vrm_0):
	if is_vrm_0:
		vrm_to_human_bone["leftThumbIntermediate"] = "LeftThumbProximal"
		vrm_to_human_bone["leftThumbProximal"] = "LeftThumbMetacarpal"
		vrm_to_human_bone["rightThumbIntermediate"] = "RightThumbProximal"
		vrm_to_human_bone["rightThumbProximal"] = "RightThumbMetacarpal"
